name: create-and-deploy-release

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      release_branch:
        description: 'Release branch where new tag should be created'
        # Default value if no value is explicitly provided
        default: 'release/1.0'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  create-release-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.release_branch }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Call gradle-release-plugin createRelease
        run: ./gradlew createRelease --stacktrace
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
  deploy-job:
    needs: create-release-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: decode key
        env:
          secringEncodingKey: ${{secrets.MC_SECRING_ENC_KEY}}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$secringEncodingKey" --output secring.gpg secring.gpg.gpgenc
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: deploy
        env:
          repositoryUrl: ${{secrets.MC_REPOSITORY_URL}}
          repositoryUser: ${{secrets.MC_REPOSITORY_USER}}
          repositoryPassword: ${{secrets.MC_REPOSITORY_PASSWORD}}
          signingKeyId: ${{secrets.MC_SIGNING_KEY_ID}}
          signingPassword: ${{secrets.MC_SIGNING_PASSWORD}}
        run: ./gradlew -PsigningSecretKeyRingFile="`pwd`/secring.gpg" -Dorg.gradle.internal.publish.checksums.insecure=true --info clean build publishToSonatype closeAndReleaseRepository
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
      - name: Cleanup
        run: |
          rm secring.gpg